import type { Product, BlogPost, Collection } from '@/types'

export const PRODUCTS: Product[] = [
  {
    id: 'callaway-rogue-st',
    name: 'Callaway Rogue ST Max',
    brand: 'Callaway',
    type: 'Driver',
    spec: '10.5°',
    condition: 'Mint',
    price: 149.99,
    rating: 4.9,
    reviewCount: 128,
    imageSrc: '/images/products/callaway-rogue-st.jpg',
    slug: 'callaway-rogue-st-max',
  },
  {
    id: 'vokey-sm9',
    name: 'Titleist Vokey SM9',
    brand: 'Titleist',
    type: 'Wedge',
    spec: '54°',
    condition: 'Good',
    price: 79.99,
    rating: 5.0,
    reviewCount: 97,
    badge: 'Top Pick',
    imageSrc: '/images/products/vokey-sm9.jpg',
    slug: 'titleist-vokey-sm9',
  },
  {
    id: 'stealth2',
    name: 'TaylorMade Stealth 2',
    brand: 'TaylorMade',
    type: 'Driver',
    spec: '9°',
    condition: 'Mint',
    price: 189.99,
    rating: 4.6,
    reviewCount: 74,
    badge: 'New In',
    imageSrc: '/images/products/stealth2.jpg',
    slug: 'taylormade-stealth-2',
  },
  {
    id: 'ping-g425-putter',
    name: 'Ping G425 Putter',
    brand: 'Ping',
    type: 'Putter',
    spec: '34"',
    condition: 'Good',
    price: 77.99,
    originalPrice: 119.99,
    rating: 4.8,
    reviewCount: 63,
    badge: '-35%',
    imageSrc: '/images/products/ping-g425-putter.jpg',
    slug: 'ping-g425-putter',
  },
  {
    id: 'cleveland-rtx6',
    name: 'Cleveland RTX6 Set',
    brand: 'Cleveland',
    type: 'Wedges',
    spec: '52°/56°',
    condition: 'Fair',
    price: 94.99,
    rating: 4.3,
    reviewCount: 41,
    imageSrc: '/images/products/cleveland-rtx6.jpg',
    slug: 'cleveland-rtx6-set',
  },
  {
    id: 'callaway-paradym',
    name: 'Callaway Paradym',
    brand: 'Callaway',
    type: 'Driver',
    spec: '',
    condition: 'Mint',
    price: 149.99,
    originalPrice: 229.99,
    rating: 4.9,
    reviewCount: 86,
    badge: '-35%',
    imageSrc: '/images/products/callaway-paradym.jpg',
    slug: 'callaway-paradym',
  },
  {
    id: 'odyssey-white-hot',
    name: 'Odyssey White Hot OG',
    brand: 'Odyssey',
    type: 'Putter',
    spec: '35"',
    condition: 'Good',
    price: 89.99,
    rating: 5.0,
    reviewCount: 112,
    imageSrc: '/images/products/odyssey-white-hot.jpg',
    slug: 'odyssey-white-hot-og',
  },
  {
    id: 'ping-g430-irons',
    name: 'Ping G430 Irons',
    brand: 'Ping',
    type: 'Irons',
    spec: '5–PW',
    condition: 'Good',
    price: 399.99,
    rating: 4.4,
    reviewCount: 55,
    badge: 'Top Pick',
    imageSrc: '/images/products/ping-g430-irons.jpg',
    slug: 'ping-g430-irons',
  },
  {
    id: 'tm-m4-wood',
    name: 'TaylorMade M4',
    brand: 'TaylorMade',
    type: '3-Wood',
    spec: '',
    condition: 'Good',
    price: 69.99,
    rating: 4.7,
    reviewCount: 38,
    imageSrc: '/images/products/tm-m4-wood.jpg',
    slug: 'taylormade-m4-3-wood',
  },
  {
    id: 'vokey-sm8',
    name: 'Titleist Vokey SM8',
    brand: 'Titleist',
    type: 'Wedge',
    spec: '56°',
    condition: 'Fair',
    price: 49.99,
    originalPrice: 99.99,
    rating: 4.2,
    reviewCount: 29,
    badge: '-50%',
    imageSrc: '/images/products/vokey-sm8.jpg',
    slug: 'titleist-vokey-sm8',
  },
]

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'blog-1',
    date: 'March 18, 2026',
    readTime: '3 min',
    title: 'How to Choose a Used Driver That Actually Fits Your Swing',
    excerpt: 'Not all pre-owned drivers are created equal. Here\'s what to look for when shopping secondhand to make sure you\'re getting a club that genuinely suits your game.',
    imageSrc: '/images/blog/blog-driver-fitting.jpg',
    slug: 'how-to-choose-a-used-driver',
  },
  {
    id: 'blog-2',
    date: 'March 10, 2026',
    readTime: '2 min',
    title: 'The 5 Most Underrated Pre-Owned Wedges Right Now',
    excerpt: 'The second-hand wedge market is full of hidden gems. We break down five models that punch above their price tag every time.',
    imageSrc: '/images/blog/blog-wedge-roundup.jpg',
    slug: 'underrated-preowned-wedges',
  },
  {
    id: 'blog-3',
    date: 'February 28, 2026',
    readTime: '4 min',
    title: 'Complete Your Bag for Under $300: A Real-World Build',
    excerpt: 'We put together a full 14-club setup using only pre-owned equipment for under three hundred dollars. Here\'s exactly what we bought and why.',
    imageSrc: '/images/blog/blog-budget-bag.jpg',
    slug: 'complete-bag-under-300',
  },
]

export const COLLECTIONS: Collection[] = [
  {
    id: 'drivers-woods',
    name: 'Drivers & Woods',
    subtitle: 'Distance. Forgiveness. Control.',
    imageSrc: '/images/lifestyle/on-course-tee-shot.jpg',
  },
  {
    id: 'irons-wedges',
    name: 'Irons & Wedges',
    subtitle: 'Precision. Consistency. Feel.',
    imageSrc: '/images/lifestyle/iron-play-closeup.jpg',
  },
]
