import type { Product, BlogPost, Collection } from '@/types'

export const CAROUSEL_PRODUCTS: Product[] = [
  {
    id: 'callaway-rogue-st',
    name: 'Callaway Rogue ST Max',
    brand: 'Callaway',
    type: 'Driver',
    spec: '10.5°',
    condition: 'Mint',
    price: 149.99,
    rating: 4.9,
    reviewCount: 128,
    imageSrc: '/images/products/callaway-rogue-st.jpg',
    slug: 'callaway-rogue-st-max',
    description: "The Rogue ST Max is Callaway's most forgiving driver, built around a Tungsten Speed Cartridge that positions weight low and deep for maximum MOI. It's the driver for golfers who want distance without sacrificing the fairway.",
    conditionNotes: "Mint condition. Face shows zero play wear. Crown is clean with no scratches. Original Callaway grip, no wear. Shaft intact with no marks. This club is indistinguishable from new.",
    specs: [
      { label: 'Loft', value: '10.5°' },
      { label: 'Lie', value: '58.5°' },
      { label: 'Shaft', value: 'Aldila Quaranta 40' },
      { label: 'Flex', value: 'Regular' },
      { label: 'Grip', value: 'Callaway Golf Pride' },
      { label: 'Length', value: '45.5"' },
      { label: 'Head Size', value: '460cc' },
      { label: 'Dexterity', value: 'Right Hand' },
    ],
    features: [
      'Tungsten Speed Cartridge for optimal CG placement',
      'Jailbreak A.I. Speed Frame for faster ball speeds',
      'Flash Face SS22 for consistent distance across the face',
      'Forged 455 Carpenter Steel face construction',
    ],
    relatedSlugs: ['taylormade-stealth-2', 'callaway-paradym', 'taylormade-m4-3-wood'],
  },
  {
    id: 'vokey-sm9',
    name: 'Titleist Vokey SM9',
    brand: 'Titleist',
    type: 'Wedge',
    spec: '54°',
    condition: 'Good',
    price: 79.99,
    rating: 5.0,
    reviewCount: 97,
    badge: 'Top Pick',
    imageSrc: '/images/products/vokey-sm9.jpg',
    slug: 'titleist-vokey-sm9',
    description: "The SM9 is the most-played wedge on Tour. Bob Vokey engineered new Spin Milled grooves and an optimised CG for each loft — this 54° is the perfect sand and approach weapon for golfers who demand precision.",
    conditionNotes: "Good condition. Face shows light play wear consistent with one season of use. Sole has minor scuff marks. Chrome finish largely intact. Grip shows light use and is fully functional.",
    specs: [
      { label: 'Loft', value: '54°' },
      { label: 'Bounce', value: '10°' },
      { label: 'Grind', value: 'S Grind' },
      { label: 'Shaft', value: 'True Temper Dynamic Gold S200' },
      { label: 'Flex', value: 'Wedge' },
      { label: 'Grip', value: 'Golf Pride Tour Velvet' },
      { label: 'Length', value: '35.5"' },
      { label: 'Dexterity', value: 'Right Hand' },
    ],
    features: [
      'Spin Milled grooves for maximum spin consistency',
      'Progressive Centre of Gravity tuned per loft',
      'Backward C-Grind for versatile sole contact',
      'Tour Chrome finish for clean address aesthetics',
    ],
    relatedSlugs: ['cleveland-rtx6-set', 'titleist-vokey-sm8', 'ping-g430-irons'],
  },
  {
    id: 'stealth2',
    name: 'TaylorMade Stealth 2',
    brand: 'TaylorMade',
    type: 'Driver',
    spec: '9°',
    condition: 'Mint',
    price: 189.99,
    rating: 4.6,
    reviewCount: 74,
    badge: 'New In',
    imageSrc: '/images/products/stealth2.jpg',
    slug: 'taylormade-stealth-2',
    description: "The Stealth 2 advances TaylorMade's carbon face technology with a 60X Carbon Twist Face that's 44% lighter than titanium. That saved weight is redistributed for optimal CG placement and one of the fastest faces in modern golf.",
    conditionNotes: "Mint condition. The iconic red carbon face is pristine with no chips or marks. Crown shows no blemishes. Shaft and grip are in like-new condition throughout.",
    specs: [
      { label: 'Loft', value: '9°' },
      { label: 'Lie', value: '59°' },
      { label: 'Shaft', value: 'Fujikura Ventus Red 5' },
      { label: 'Flex', value: 'Stiff' },
      { label: 'Grip', value: 'Golf Pride Z-Grip' },
      { label: 'Length', value: '45.75"' },
      { label: 'Head Size', value: '460cc' },
      { label: 'Dexterity', value: 'Right Hand' },
    ],
    features: [
      '60X Carbon Twist Face — 44% lighter than titanium',
      'Thru-Slot Speed Pocket for low-face ball speed',
      'Inertia Generator for increased swing stability',
      'Nanotexture PU cover reduces spin in variable conditions',
    ],
    relatedSlugs: ['callaway-rogue-st-max', 'callaway-paradym', 'taylormade-m4-3-wood'],
  },
  {
    id: 'ping-g425-putter',
    name: 'Ping G425 Putter',
    brand: 'Ping',
    type: 'Putter',
    spec: '34"',
    condition: 'Good',
    price: 77.99,
    originalPrice: 119.99,
    rating: 4.8,
    reviewCount: 63,
    badge: '-35%',
    imageSrc: '/images/products/ping-g425-putter.jpg',
    slug: 'ping-g425-putter',
    description: "The G425 Anser putter from Ping is engineered for consistency. A precision-milled face with a dual-durometer insert provides soft, responsive feel that holds its own against putters twice the price.",
    conditionNotes: "Good condition. Face insert shows light wear consistent with regular play. Crown alignment line intact and clearly visible. Sole has minor cart bag scuffs. Grip is lightly worn but fully functional.",
    specs: [
      { label: 'Style', value: 'Blade / Anser' },
      { label: 'Length', value: '34"' },
      { label: 'Loft', value: '3°' },
      { label: 'Lie', value: '70°' },
      { label: 'Grip', value: 'Ping PP60' },
      { label: 'Offset', value: 'Full Shaft' },
      { label: 'Dexterity', value: 'Right Hand' },
    ],
    features: [
      'Dual-durometer PEBAX face insert for soft, consistent feel',
      'True Roll face milling for repeatable speed at impact',
      'Precision machined 303 stainless steel construction',
      'Stability Shaft reduces torque through the stroke',
    ],
    relatedSlugs: ['odyssey-white-hot-og', 'callaway-paradym', 'titleist-vokey-sm9'],
  },
  {
    id: 'cleveland-rtx6',
    name: 'Cleveland RTX6 Set',
    brand: 'Cleveland',
    type: 'Wedges',
    spec: '52°/56°',
    condition: 'Fair',
    price: 94.99,
    rating: 4.3,
    reviewCount: 41,
    imageSrc: '/images/products/cleveland-rtx6.jpg',
    slug: 'cleveland-rtx6-set',
    description: "The RTX 6 ZipCore is Cleveland's most advanced wedge design. A hollow low-density core rebalances the CG closer to the face for more spin and better distance control. This two-wedge set covers your gap and sand game completely.",
    conditionNotes: "Fair condition. Face shows play wear consistent with regular use — grooves remain sharp and fully functional. Sole wear is visible but expected. Some finish discolouration on the hosel. Grips show moderate use.",
    specs: [
      { label: 'Set Includes', value: '52° + 56°' },
      { label: '52° Bounce', value: '10°' },
      { label: '56° Bounce', value: '12°' },
      { label: 'Grind', value: 'Full-Face (both)' },
      { label: 'Shaft', value: 'Dynamic Gold Spinner' },
      { label: 'Grip', value: 'Lamkin Crossline (both)' },
      { label: 'Dexterity', value: 'Right Hand' },
    ],
    features: [
      'ZipCore technology recentres CG for consistent spin',
      "UltiZip Grooves — Cleveland's sharpest groove profile ever",
      'Laser Milled micro-texture face for added wedge spin',
      'Full-Face grind supports open-face shot making',
    ],
    relatedSlugs: ['titleist-vokey-sm9', 'titleist-vokey-sm8', 'ping-g430-irons'],
  },
]

export const BESTSELLER_PRODUCTS: Product[] = [
  {
    id: 'callaway-paradym',
    name: 'Callaway Paradym',
    brand: 'Callaway',
    type: 'Driver',
    spec: '',
    condition: 'Mint',
    price: 149.99,
    originalPrice: 229.99,
    rating: 4.9,
    reviewCount: 86,
    badge: '-35%',
    imageSrc: '/images/products/callaway-paradym.jpg',
    slug: 'callaway-paradym',
    description: "The Paradym combines a full carbon chassis — crown, sole, and skirt — to save more weight than any previous Callaway driver. That saved mass is redistributed into a Tungsten Speed Cartridge for maximum distance and optimal ball flight.",
    conditionNotes: "Mint condition. The full carbon body is flawless — no chips, cracks, or surface marks. Face is completely clean. Grip is pristine. This club has clearly had minimal play time.",
    specs: [
      { label: 'Loft', value: '10.5°' },
      { label: 'Lie', value: '58.5°' },
      { label: 'Shaft', value: 'Project X HZRDUS Silver 60' },
      { label: 'Flex', value: 'Regular' },
      { label: 'Grip', value: 'Golf Pride Tour Velvet 360' },
      { label: 'Length', value: '45.5"' },
      { label: 'Head Size', value: '460cc' },
      { label: 'Dexterity', value: 'Right Hand' },
    ],
    features: [
      'Full triaxial carbon body — lightest Callaway chassis ever built',
      'Tungsten Speed Cartridge for precise CG and ball flight optimisation',
      'Jailbreak Speed Frame stiffens the body for maximum energy transfer',
      'AI-designed Flash Face SS22 for consistent speed across the face',
    ],
    relatedSlugs: ['callaway-rogue-st-max', 'taylormade-stealth-2', 'taylormade-m4-3-wood'],
  },
  {
    id: 'odyssey-white-hot',
    name: 'Odyssey White Hot OG',
    brand: 'Odyssey',
    type: 'Putter',
    spec: '35"',
    condition: 'Good',
    price: 89.99,
    rating: 5.0,
    reviewCount: 112,
    imageSrc: '/images/products/odyssey-white-hot.jpg',
    slug: 'odyssey-white-hot-og',
    description: "The White Hot OG brings back the insert that made Odyssey famous. The original White Hot material provides that unmistakable soft, responsive feel that generations of Tour players have trusted on the greens for decades.",
    conditionNotes: "Good condition. White Hot insert shows light play marks — feel and roll performance are fully intact. Sole has minor scuffs. Grip shows light wear. Overall a very clean example of this model.",
    specs: [
      { label: 'Style', value: 'Blade (#7)' },
      { label: 'Length', value: '35"' },
      { label: 'Loft', value: '3°' },
      { label: 'Lie', value: '70°' },
      { label: 'Grip', value: 'Odyssey Pistol' },
      { label: 'Offset', value: 'Half Shaft' },
      { label: 'Dexterity', value: 'Right Hand' },
    ],
    features: [
      'Original White Hot urethane insert — the feel that defined a generation',
      'Precision milled 304 stainless steel head construction',
      '100g tungsten weighting positioned for stable, consistent roll',
      'Available in multiple head shapes — this is the #7 blade',
    ],
    relatedSlugs: ['ping-g425-putter', 'cleveland-rtx6-set', 'titleist-vokey-sm9'],
  },
  {
    id: 'ping-g430-irons',
    name: 'Ping G430 Irons',
    brand: 'Ping',
    type: 'Irons',
    spec: '5–PW',
    condition: 'Good',
    price: 399.99,
    rating: 4.4,
    reviewCount: 55,
    badge: 'Top Pick',
    imageSrc: '/images/products/ping-g430-irons.jpg',
    slug: 'ping-g430-irons',
    description: "The G430 iron set is Ping's most forgiving cavity-back design. A custom-tuned face insert and ECHO Damping System combine to deliver explosive ball speed with a soft, muted feel that makes the forgiveness invisible at impact.",
    conditionNotes: "Good condition. Faces show light play wear consistent with one season of use — grooves are sharp and fully functional. Soles have expected scuffing. Chrome finish on all six heads is largely intact. Grips show light use.",
    specs: [
      { label: 'Set Includes', value: '5, 6, 7, 8, 9, PW' },
      { label: 'Construction', value: 'Cast 17-4 Stainless Steel' },
      { label: 'Shaft', value: 'True Temper Elevate Tour 95' },
      { label: 'Flex', value: 'Regular' },
      { label: 'Grip', value: 'Ping PP60 (all irons)' },
      { label: '7-Iron Loft', value: '31°' },
      { label: 'Offset', value: 'Progressive' },
      { label: 'Dexterity', value: 'Right Hand' },
    ],
    features: [
      'Custom Tuning Port (CTP) for precise sound and feel at impact',
      'ECHO Damping System reduces unwanted vibration significantly',
      'Hydropearl 2.0 chrome finish for improved wet-weather performance',
      'Facewrap technology extends the CTP zone across the entire face',
    ],
    relatedSlugs: ['callaway-rogue-st-max', 'cleveland-rtx6-set', 'titleist-vokey-sm8'],
  },
  {
    id: 'tm-m4-wood',
    name: 'TaylorMade M4',
    brand: 'TaylorMade',
    type: '3-Wood',
    spec: '',
    condition: 'Good',
    price: 69.99,
    rating: 4.7,
    reviewCount: 38,
    imageSrc: '/images/products/tm-m4-wood.jpg',
    slug: 'taylormade-m4-3-wood',
    description: "The M4 fairway wood remains one of TaylorMade's most beloved designs. Ribcor technology stiffens the outer perimeter of the face while the Speed Pocket flexes independently for added ball speed on low-face contact.",
    conditionNotes: "Good condition. Crown shows light scuffs consistent with normal bag and play wear. Face is clean. Sole has minor marks. Shaft and grip are in excellent condition throughout.",
    specs: [
      { label: 'Loft', value: '15°' },
      { label: 'Lie', value: '56.5°' },
      { label: 'Shaft', value: 'Fujikura Atmos Orange 6' },
      { label: 'Flex', value: 'Stiff' },
      { label: 'Grip', value: 'Golf Pride Align' },
      { label: 'Length', value: '43"' },
      { label: 'Head Size', value: '175cc' },
      { label: 'Dexterity', value: 'Right Hand' },
    ],
    features: [
      'Ribcor technology increases face COR across the hitting zone',
      'Twist Face corrects the most common off-centre miss patterns',
      'Speed Pocket enables low-face ball speed that rivals centre hits',
      'Ultra-low CG placement produces high, penetrating ball flight',
    ],
    relatedSlugs: ['callaway-rogue-st-max', 'taylormade-stealth-2', 'ping-g430-irons'],
  },
  {
    id: 'vokey-sm8',
    name: 'Titleist Vokey SM8',
    brand: 'Titleist',
    type: 'Wedge',
    spec: '56°',
    condition: 'Fair',
    price: 49.99,
    originalPrice: 99.99,
    rating: 4.2,
    reviewCount: 29,
    badge: '-50%',
    imageSrc: '/images/products/vokey-sm8.jpg',
    slug: 'titleist-vokey-sm8',
    description: "The SM8 redefined what a worn wedge can still deliver. The progressive CG shift between lofts gives each wedge its own optimised spin window. A full season of play barely touches the performance — and the price reflects that honestly.",
    conditionNotes: "Fair condition. Face shows visible groove wear from regular play. Sole has scuffs and the finish shows some discolouration. Grooves remain functional. This is an honest club priced accordingly — it performs.",
    specs: [
      { label: 'Loft', value: '56°' },
      { label: 'Bounce', value: '10°' },
      { label: 'Grind', value: 'M Grind' },
      { label: 'Shaft', value: 'True Temper Dynamic Gold S200' },
      { label: 'Flex', value: 'Wedge' },
      { label: 'Grip', value: 'Golf Pride Tour Velvet' },
      { label: 'Length', value: '35.5"' },
      { label: 'Dexterity', value: 'Right Hand' },
    ],
    features: [
      'Progressive CG — independently optimised per every 2° of loft',
      'Spin Milled 8 grooves for consistent spin rates across conditions',
      "M Grind is Titleist's most versatile option for bunker and rough play",
      'Tour Chrome finish — honest play patina, full performance intact',
    ],
    relatedSlugs: ['titleist-vokey-sm9', 'cleveland-rtx6-set', 'ping-g430-irons'],
  },
]

export const PRODUCTS: Product[] = [...CAROUSEL_PRODUCTS, ...BESTSELLER_PRODUCTS]

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'blog-1',
    date: 'March 18, 2026',
    readTime: '3 min',
    title: 'How to Choose a Used Driver That Actually Fits Your Swing',
    excerpt: 'Not all pre-owned drivers are created equal. Here\'s what to look for when shopping secondhand to make sure you\'re getting a club that genuinely suits your game.',
    imageSrc: '/images/blog/blog-driver-fitting.jpg',
    slug: 'how-to-choose-a-used-driver',
  },
  {
    id: 'blog-2',
    date: 'March 10, 2026',
    readTime: '2 min',
    title: 'The 5 Most Underrated Pre-Owned Wedges Right Now',
    excerpt: 'The second-hand wedge market is full of hidden gems. We break down five models that punch above their price tag every time.',
    imageSrc: '/images/blog/blog-wedge-roundup.jpg',
    slug: 'underrated-preowned-wedges',
  },
  {
    id: 'blog-3',
    date: 'February 28, 2026',
    readTime: '4 min',
    title: 'Complete Your Bag for Under $300: A Real-World Build',
    excerpt: 'We put together a full 14-club setup using only pre-owned equipment for under three hundred dollars. Here\'s exactly what we bought and why.',
    imageSrc: '/images/blog/blog-budget-bag.jpg',
    slug: 'complete-bag-under-300',
  },
]

export const COLLECTIONS: Collection[] = [
  {
    id: 'drivers-woods',
    name: 'Drivers & Woods',
    subtitle: 'Distance. Forgiveness. Control.',
    imageSrc: '/images/sections/collection-drivers-woods.jpg',
  },
  {
    id: 'irons-wedges',
    name: 'Irons & Wedges',
    subtitle: 'Precision. Consistency. Feel.',
    imageSrc: '/images/sections/collection-irons-wedges.jpg',
  },
]
